title: Little eyes
author: zhongweili
email: lizhongwei.nkcs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  random thoughts and random notes.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
